[Git]
default_remote = origin

[GitHub]
token = 
user = 
email = 
repo = dockerfiles
repo_owner = pegi3s
branch = master

[Gemini]
api_key = 
model = 

[Remote]
host = 
username = 
password = 
dir = 

[DockerHub]
user = 
token = 
org = pegi3s

[BDIPTools]
config_path = 
metadata_path = 
results_path = 
tools_folder = 
project_path = 

[Dockerfiles]
#location of onthology dioa.diaf file
path = 
